# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FromOrbit.com
title_separator: "|"
name: "Alan Garfield"
description: >
    Generic nerd who dabbles in programming, electronics, CNC and retro computing.
url: "https://fromorbit.com"
baseurl: ""
timezone: Australia/Sydney

image_url: /assets/images
sizes: '(max-width: 600px) 100vw, (max-width: 900px) 33vw, 500px'
srcset:
  - 320
  - 640
  - 1280

teaser: /assets/images/500x300.png

locale: "en"
markdown: kramdown

theme: minimal-mistakes-jekyll

paginate: 15 # amount of posts to show
paginate_path: /page:num/

author:
  name   : "Alan Garfield"
  avatar : "/assets/bio.jpg"
  bio    : "Generic nerd who dabbles in programming, electronics, CNC and retro computing."
  twitter: "alangarf"
  github:  "alangarf"
  youtube:  "randomgarfield"

compress_html:
  clippings: all

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true

twitter:
  username: "alangarf"      

comments:
  provider: "disqus"
  disqus:
    shortname: "fromorbit-com"      

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-1867259-2"    

#header:
#    image: "/images/fromorbit_header.gif"
#    height: 120

#disqus:
#    shortname: fromorbit-com

#google_analytics: UA-1867259-2

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile', 'Makefile']
include: ['.nojekyll']

gems:
  - jekyll-paginate    
